#!yml

image: maven:3.6.1

pipelines:
  custom:
    deploy:
      - step:
          script:
            - git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master